# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: check-merge-conflict
      - id: name-tests-test
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.2
    hooks:
      - id: flake8
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: protect-first-parent
  - repo: local
    hooks:
      - id: commitizen
        name: My commitizen check
        entry: cz
        args: ["check", "--commit-msg-file", ".git/COMMIT_EDITMSG"]
        pass_filenames: false
        language: system
        stages: [commit-msg]
